baseURL = "https://arthurgao.ca"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Arthur Gao"

# theme as hugo module
theme = "github.com/lxndrblz/anatole"
# theme as git submodule
#theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
