  [[main]]
  name = "About"
  weight = 100
  identifier = "about"
  url = "/"

  [[main]]
  name = "Portfolio"
  weight = 200
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"